version: 2
updates:
  - package-ecosystem: npm
    directory: /runtimes/pi
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
  - package-ecosystem: npm
    directory: /runtimes/dsh
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
