param([Parameter(Mandatory = $true)][string]$Executable)
$ErrorActionPreference='Stop'
$Executable=(Resolve-Path -LiteralPath $Executable).Path
function Wait-Until([scriptblock]$Action,[scriptblock]$Predicate,[int]$Seconds=30){$expires=(Get-Date).AddSeconds($Seconds);do{Start-Sleep -Milliseconds 80;try{$value=& $Action}catch{$value=$null};if(&$Predicate $value){return $value}}while((Get-Date) -lt $expires);throw ('Timed out waiting for M3 queue state: '+[string]$script:stage)}
function Connect-Host([string]$RuntimePath,[int]$PreviousPid=0){$runtime=Wait-Until{try{if(Test-Path $RuntimePath){Get-Content $RuntimePath -Raw -Encoding UTF8|ConvertFrom-Json}}catch{$null}}{param($v)$null -ne $v -and $v.state -eq 'running' -and [int]$v.pid -ne $PreviousPid};Add-Type -AssemblyName System.Security;$plain=[Security.Cryptography.ProtectedData]::Unprotect([Convert]::FromBase64String([string]$runtime.authProtected),$null,[Security.Cryptography.DataProtectionScope]::CurrentUser);@{Runtime=$runtime;Base="http://127.0.0.1:$($runtime.port)";Headers=@{'X-Desktop-Secret'=[Text.Encoding]::UTF8.GetString($plain);'X-Workbench-Protocol'='2'}}}
function Api($Connection,[string]$Path,[string]$Method='GET',$Body=$null){$request=@{Uri=$Connection.Base+$Path;Headers=$Connection.Headers;Method=$Method};if($null -ne $Body){$request.ContentType='application/json; charset=utf-8';$request.Body=[Text.Encoding]::UTF8.GetBytes(($Body|ConvertTo-Json -Depth 12 -Compress))};Invoke-RestMethod @request}
$root=Join-Path ([IO.Path]::GetTempPath()) ('claude-m3-queue-'+[guid]::NewGuid().ToString('N'));[IO.Directory]::CreateDirectory($root)|Out-Null
$fake=Join-Path $root 'fake-claude.exe';$vsRoot='C:\Program Files\Microsoft Visual Studio\2022\Community';$csc=Join-Path $vsRoot 'MSBuild\Current\Bin\Roslyn\csc.exe';$json=Join-Path $vsRoot 'Common7\IDE\CommonExtensions\Microsoft\NuGet\Newtonsoft.Json.dll';&$csc /nologo /target:exe /platform:x64 "/out:$fake" "/reference:$json" (Join-Path $PSScriptRoot 'fake-claude-worker.cs');if($LASTEXITCODE -ne 0){throw 'Fake worker build failed'};Copy-Item $json (Join-Path $root 'Newtonsoft.Json.dll')
$env:CLAUDE_GUI_WORKSPACE=$root;$env:CLAUDE_GUI_ROOT='D:\softwares\ClaudeCode';$env:CLAUDE_GUI_CLAUDE_EXE=$fake;$env:CLAUDE_GUI_TEST_MODE='1';$env:CLAUDE_GUI_MUTEX_SCOPE='m3-'+[guid]::NewGuid().ToString('N');$runtimePath=Join-Path $root '.claude-gui-v2\runtime-state.json'
$hostProcess=$null
try{
 $script:stage='initial Host startup';$hostProcess=Start-Process $Executable -ArgumentList '--host' -WorkingDirectory $root -WindowStyle Hidden -PassThru;$connection=Connect-Host $runtimePath
 Api $connection '/api/providers' 'POST' @{id='offline-q';name='Offline Queue';token='stub';authStyle='bearer';text=@{enabled=$true;protocol='openai';baseUrl='http://127.0.0.1:9/v1';models=@('offline')};image=@{enabled=$false;protocol='openai-images';baseUrl='';models=@()}}|Out-Null
 $session=[guid]::NewGuid().ToString();$request=@{workspace=$root;attachments=@();allowedDirs=@();sessionId=$session;claudeSessionId=$session;resume=$true;providerId='offline-q';model='offline';effort='low';permissionMode='readonly';allowedTools=@();disallowedTools=@()}
 $first=Api $connection '/api/task-queue' 'POST' @{sessionId=$session;text='fault-recovery-first';kind='queued';request=$request};$second=Api $connection '/api/task-queue' 'POST' @{sessionId=$session;text='queue-second';kind='queued';request=$request}
 $script:stage='first queue item running';$running=Wait-Until{Api $connection ("/api/task-queue?sessionId=$session&history=1")}{param($v)@($v|Where-Object id -eq $first.id|Where-Object state -eq 'running').Count -eq 1}
 $oldPid=[int]$connection.Runtime.pid;Stop-Process -Id $oldPid -Force;Start-Sleep -Milliseconds 250;$script:stage='replacement Host startup';$hostProcess=Start-Process $Executable -ArgumentList '--host' -WorkingDirectory $root -WindowStyle Hidden -PassThru;$connection=Connect-Host $runtimePath $oldPid
 $script:stage='running queue recovery';$restored=Wait-Until{Api $connection ("/api/task-queue?sessionId=$session&history=1")}{param($v)@($v|Where-Object id -eq $first.id|Where-Object state -eq 'running').Count -eq 1}
 $third=Api $connection '/api/task-queue' 'POST' @{sessionId=$session;text='queue-steer';kind='queued';request=$request};Api $connection ("/api/task-queue/prioritize/$($third.id)") 'POST' @{steer=$true}|Out-Null
 $script:stage='all prioritized queue items completed';$history=Wait-Until{Api $connection ("/api/task-queue?sessionId=$session&history=1")}{param($v)@($v).Count -eq 3 -and @($v|Where-Object state -eq 'completed').Count -eq 3} 35
 $runId=($history|Where-Object id -eq $first.id).runId;$poll=Api $connection ("/api/chat/poll/$($runId)?after=0");$results=@($poll.events|Where-Object{$_.payload-match '"type":"result"'})
 if($results.Count -ne 3){throw "Expected 3 queue results, got $($results.Count)"};$joined=@($results.payload)-join "`n";$a=$joined.IndexOf('fault-recovery-first');$b=$joined.IndexOf('queue-steer');$c=$joined.IndexOf('queue-second');if($a -lt 0 -or $b -lt $a -or $c -lt $b){throw 'Queue or steer order was not preserved'}
 [pscustomobject]@{DurableQueue='OK';HostRestartRecovery='OK';LiveSteer='OK';FifoInputAck='OK';QueueOrder='first -> steer -> second';ResultCount=$results.Count;OldHostPid=$oldPid;NewHostPid=$connection.Runtime.pid;Root=$root}|Format-List
}finally{Get-CimInstance Win32_Process|Where-Object{$_.ExecutablePath -eq $Executable -or $_.ExecutablePath -eq $fake}|ForEach-Object{Stop-Process -Id $_.ProcessId -Force -ErrorAction SilentlyContinue};Remove-Item Env:CLAUDE_GUI_WORKSPACE,Env:CLAUDE_GUI_ROOT,Env:CLAUDE_GUI_CLAUDE_EXE,Env:CLAUDE_GUI_TEST_MODE,Env:CLAUDE_GUI_MUTEX_SCOPE -ErrorAction SilentlyContinue}
