param([Parameter(Mandatory = $true)][string]$Executable)
$ErrorActionPreference='Stop'
$Executable=(Resolve-Path -LiteralPath $Executable).Path
function Wait-Value([scriptblock]$Action,[scriptblock]$Predicate,[int]$Seconds=20){$end=(Get-Date).AddSeconds($Seconds);do{Start-Sleep -Milliseconds 100;$value=&$Action;if(&$Predicate $value){return $value}}while((Get-Date)-lt$end);throw 'Timed out waiting for Host'}
function Connect([string]$Path,[int]$OldPid=0){$state=Wait-Value {try{Get-Content -Raw -Encoding UTF8 -LiteralPath $Path|ConvertFrom-Json}catch{$null}} {param($v)$v-and$v.state-eq'running'-and[int]$v.pid-ne$OldPid};Add-Type -AssemblyName System.Security;$plain=[Security.Cryptography.ProtectedData]::Unprotect([Convert]::FromBase64String([string]$state.authProtected),$null,[Security.Cryptography.DataProtectionScope]::CurrentUser);@{Runtime=$state;Secret=[Text.Encoding]::UTF8.GetString($plain);Base="http://127.0.0.1:$($state.port)";Headers=@{'X-Desktop-Secret'=[Text.Encoding]::UTF8.GetString($plain);'X-Workbench-Protocol'='2'}}}
function Api($c,[string]$Path,[string]$Method='GET',$Body=$null){$args=@{Uri=$c.Base+$Path;Headers=$c.Headers;Method=$Method};if($null-ne$Body){$args.ContentType='application/json; charset=utf-8';$args.Body=[Text.Encoding]::UTF8.GetBytes(($Body|ConvertTo-Json -Depth 10 -Compress))};Invoke-RestMethod @args}
$root=Join-Path ([IO.Path]::GetTempPath()) ('claude-permission-restart-'+[guid]::NewGuid().ToString('N'));[IO.Directory]::CreateDirectory($root)|Out-Null
$env:CLAUDE_GUI_WORKSPACE=$root;$env:CLAUDE_GUI_ROOT='D:\softwares\ClaudeCode';$env:CLAUDE_GUI_TEST_MODE='1';$env:CLAUDE_GUI_MUTEX_SCOPE='permission-'+[guid]::NewGuid().ToString('N')
$runtime=Join-Path $root '.claude-gui-v2\runtime-state.json';$process=Start-Process $Executable -ArgumentList '--host' -WorkingDirectory $root -WindowStyle Hidden -PassThru;$connection=$null
try{
 $connection=Connect $runtime;$runId=[guid]::NewGuid().ToString();$sessionId=[guid]::NewGuid().ToString();$runDir=Join-Path $root ".claude-gui-v2\runs\$runId";[IO.Directory]::CreateDirectory($runDir)|Out-Null
 $request=@{guiSessionId=$sessionId;sessionId=$sessionId;sourceWorkspace=$root;workspace=$root;model='offline-manual'}|ConvertTo-Json -Compress;[IO.File]::WriteAllText((Join-Path $runDir 'request.json'),$request,[Text.UTF8Encoding]::new($false))
 $policy=@{schemaVersion=1;jobId=$runId;mode='manual';workspace=$root;roots=@($root);writeRoots=@($root);capabilities=@{read='allow';write='ask';delete='ask';execute='ask';network='ask';unknown='ask'};allowedTools=@();disallowedTools=@()}|ConvertTo-Json -Depth 8 -Compress;[IO.File]::WriteAllText((Join-Path $runDir 'security-policy.json'),$policy,[Text.UTF8Encoding]::new($false))
 $created=Api $connection '/api/permissions/request' 'POST' @{jobId=$runId;toolName='Write';input=@{file_path=(Join-Path $root '中文.txt');content='fixture';api_key='must-be-redacted'}}
 if($created.state-ne'pending'-or[bool]$created.automatic){throw 'Manual approval was not pending'}
 $pending=@(Api $connection '/api/permissions/pending');$item=$pending|Where-Object{$_.id -eq $created.id}|Select-Object -First 1
 if($item.sessionId -ne $sessionId -or $item.workspace -ne $root -or $item.model -ne 'offline-manual'){throw ('Approval attribution is incomplete: item='+($item|ConvertTo-Json -Depth 8 -Compress)+' pending='+($pending|ConvertTo-Json -Depth 8 -Compress)+' created='+($created|ConvertTo-Json -Compress))}
 if(($item|ConvertTo-Json -Depth 8)-match'must-be-redacted'){throw 'Approval public payload leaked a secret'}
 $oldPid=[int]$connection.Runtime.pid;$oldSecret=$connection.Secret;Stop-Process -Id $oldPid -Force;Start-Sleep -Milliseconds 400;$process=Start-Process $Executable -ArgumentList '--host' -WorkingDirectory $root -WindowStyle Hidden -PassThru;$connection=Connect $runtime $oldPid
 if($connection.Secret-ne$oldSecret){throw 'Host credential changed across restart and would strand an existing Permission MCP'}
 $restored=@(Api $connection '/api/permissions/pending');$restoredMatch=@($restored|Where-Object{$_.id -eq $created.id});if($restoredMatch.Count -ne 1){throw ('Pending approval did not survive Host restart: '+($restored|ConvertTo-Json -Depth 8 -Compress))}
 $recoveryPid=[int]$connection.Runtime.pid;Stop-Process -Id $recoveryPid -Force;[IO.File]::WriteAllText((Join-Path $root '.claude-gui-v2\host-auth.json'),'{"authProtected":"corrupt"}',[Text.UTF8Encoding]::new($false));Start-Sleep -Milliseconds 400;$process=Start-Process $Executable -ArgumentList '--host' -WorkingDirectory $root -WindowStyle Hidden -PassThru;$connection=Connect $runtime $recoveryPid
 if($connection.Secret-ne$oldSecret){throw 'Host did not recover its credential from runtime-state after auth file corruption'}
 Api $connection '/api/permissions/respond' 'POST' @{id=$created.id;behavior='allow';message=''}|Out-Null;$result=Api $connection "/api/permissions/result/$($created.id)";if($result.state-ne'completed'-or$result.decision.behavior-ne'allow'){throw 'Recovered approval decision did not roundtrip'}
 $secondPid=[int]$connection.Runtime.pid;Stop-Process -Id $secondPid -Force;Start-Sleep -Milliseconds 400;$process=Start-Process $Executable -ArgumentList '--host' -WorkingDirectory $root -WindowStyle Hidden -PassThru;$connection=Connect $runtime $secondPid
 $after=Api $connection '/api/permissions/pending';$afterJson=$after|ConvertTo-Json -Depth 8 -Compress;if($afterJson -and $afterJson -ne '[]'){throw ('Consumed approval was resurrected after restart: '+$afterJson)}
 [pscustomobject]@{DurableApproval='PASS';HostCredentialContinuity='PASS';CorruptAuthRecovery='PASS';Attribution='PASS';SecretRedaction='PASS';ConsumedState='PASS';InitialPid=$oldPid;FinalPid=$connection.Runtime.pid;Workspace=$root}|Format-List
}finally{if($connection){Stop-Process -Id ([int]$connection.Runtime.pid) -Force -ErrorAction SilentlyContinue};Remove-Item Env:CLAUDE_GUI_WORKSPACE,Env:CLAUDE_GUI_ROOT,Env:CLAUDE_GUI_TEST_MODE,Env:CLAUDE_GUI_MUTEX_SCOPE -ErrorAction SilentlyContinue}
